services:
  backend:
    build: backend
    container_name: repeater-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/scripts:/app/scripts
      - ./backend/alembic:/app/alembic

    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/repeater
      - SECRET_KEY=abc123

    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock

    depends_on:
      db:
        condition: service_healthy

  web:
    build: 
      context: web
      target: development
    container_name: repeater-web

    ports:
      - "3000:3000"

    volumes:
      - ./web:/app
      - /app/node_modules

    develop:
      watch:
        - action: sync
          path: web
          target: /app
          ignore:
            - node_modules/
            - .next/

    environment:
      - NODE_ENV=development

  db:
    image: postgres:17

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repeater

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d repeater"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
