services:
  backend:
    build: backend

    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
