services:
  backend:
    build: backend
    container_name: repeater-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
      - ./backend/scripts:/app/scripts
      - ./backend/docs:/app/docs

    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./uv.lock
