[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.1",
    "authlib>=1.6.0",
    "bcrypt>=4.3.0",
    "dacite>=1.9.2",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.115.12",
    "freezegun>=1.5.2",
    "itsdangerous>=2.2.0",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.5",
    "pyjwt>=2.10.1",
    "pytest-asyncio>=1.0.0",
    "sqlalchemy>=2.0.41",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.0",
]
[tool.pytest.ini_options]
asyncio_mode = "auto"
minversion = "6.0"
testpaths = [
    "tests",
]
