"""Remove categories and use hierarchical decks

Revision ID: 2164e7d37b72
Revises: 56dd6c609bb7
Create Date: 2025-08-31 09:56:38.956364

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2164e7d37b72"
down_revision: Union[str, None] = "56dd6c609bb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("decks", sa.Column("parent_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("decks_category_id_fkey"), "decks", type_="foreignkey")
    op.drop_column("decks", "category_id")
    op.drop_table("categories")
    op.create_foreign_key(None, "decks", "decks", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "decks", sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "decks", type_="foreignkey")
    op.create_foreign_key(
        op.f("decks_category_id_fkey"), "decks", "categories", ["category_id"], ["id"]
    )
    op.drop_column("decks", "parent_id")
    op.create_table(
        "categories",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["categories.id"], name=op.f("categories_parent_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("categories_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("categories_pkey")),
    )
    # ### end Alembic commands ###
