"""Add is_paused to deck

Revision ID: 56dd6c609bb7
Revises: b75469aa6007
Create Date: 2025-07-27 14:39:42.733023

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56dd6c609bb7"
down_revision: Union[str, None] = "b75469aa6007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("decks", sa.Column("is_paused", sa.Boolean(), nullable=False))
    op.alter_column("decks", "is_archived", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("decks", "is_archived", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("decks", "is_paused")
    # ### end Alembic commands ###
