"""add review undo fields

Revision ID: 6ba02ca7f07d
Revises: 2164e7d37b72
Create Date: 2026-05-03 12:24:20.273707

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ba02ca7f07d"
down_revision: Union[str, None] = "2164e7d37b72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reviews",
        sa.Column(
            "previous_next_review_date", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "reviews",
        sa.Column("next_review_date", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "reviews", sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "undone_at")
    op.drop_column("reviews", "next_review_date")
    op.drop_column("reviews", "previous_next_review_date")
    # ### end Alembic commands ###
