"""Make password_hash nullable and add auth_provider

Revision ID: a7e545f74db4
Revises: cde8d9c509c0
Create Date: 2025-07-01 09:02:37.745645

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7e545f74db4"
down_revision: Union[str, None] = "cde8d9c509c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_provider", sa.String(), nullable=False))
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "auth_provider")
    # ### end Alembic commands ###
