"""Add is_archived to deck

Revision ID: b75469aa6007
Revises: ef1d4910dcf5
Create Date: 2025-07-26 08:07:28.879031

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b75469aa6007"
down_revision: Union[str, None] = "ef1d4910dcf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("decks", sa.Column("is_archived", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("decks", "is_archived")
    # ### end Alembic commands ###
