"""Make reviews' card_id nullable

Revision ID: beef753ab424
Revises: edcb0f37ea88
Create Date: 2025-07-20 08:02:43.501046

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'beef753ab424'
down_revision: Union[str, None] = 'edcb0f37ea88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'card_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'card_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
