"""Update review table, remove relation to card

Revision ID: ef1d4910dcf5
Revises: edcb0f37ea88
Create Date: 2025-07-20 18:59:54.207502

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef1d4910dcf5"
down_revision: Union[str, None] = "edcb0f37ea88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("deck_id", sa.UUID(), nullable=False))
    op.add_column("reviews", sa.Column("card_content", sa.String(), nullable=True))
    op.add_column("reviews", sa.Column("deck_name", sa.String(), nullable=False))
    op.add_column(
        "reviews", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.drop_constraint(op.f("reviews_card_id_fkey"), "reviews", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("reviews_card_id_fkey"), "reviews", "cards", ["card_id"], ["id"]
    )
    op.drop_column("reviews", "updated_at")
    op.drop_column("reviews", "deck_name")
    op.drop_column("reviews", "card_content")
    op.drop_column("reviews", "deck_id")
    # ### end Alembic commands ###
