openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /auth/login:
    post:
      tags:
      - auth
      summary: Login
      operationId: login_auth_login_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /auth/register:
    post:
      tags:
      - auth
      summary: Register
      operationId: register_auth_register_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
