name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: repeater
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install UV
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install dependencies
        run: uv sync
        working-directory: ./backend
      
      - name: Run backend formatting check
        run: |
          uvx run ruff check --select I .
          uvx run ruff format --check .
        working-directory: ./backend
      
      - name: Run tests
        run: uv run pytest
        env:
          DATABASE_URL: postgresql://user:password@db:5432/repeater
          SECRET_KEY: abc123
          FRONTEND_URL: .
        working-directory: ./backend

  frontend-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install frontend dependencies
        run: pnpm install
        working-directory: ./web
      
      - name: Run frontend formatting check
        run: |
          pnpm run lint
          pnpm exec prettier --check .
        working-directory: ./web
